---

- include: install_homebrew.yml
  tags: osx_install_homebrew
  
- include: install_ruby.yml
  tags: osx_install_ruby

- include: install_nodejs.yml
  tags: osx_install_nodejs

- include: install_xcode.yml
  tags: osx_install_xcode

- include: download_certs.yml
  tags: osx_download_certs

- include: pod_repo_update.yml
  tags: osx_pod_repo_update

- include: configure_buildfarm_node.yml
  tags: osx_configure_buildfarm

- include: configure_buildfarm_proxy.yml
  tags: osx_configure_proxy
